services:
  - type: web
    name: xclusive-backend
    env: docker
    branch: main
    region: virginia
    rootDir: backend
    plan: free
    envVars:
      - key: ODDS_API_KEY
      - key: DATABASE_URL
      - key: JWT_SECRET_KEY
    buildCommand: |
      python -m pip install --upgrade pip && \
      python -m pip install -r requirements.txt && \
      playwright install-deps && \
      playwright install
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 3
    healthCheckPath: /ping

  - type: web
    name: xclusive-frontend
    env: node
    branch: main
    region: virginia
    rootDir: frontend
    plan: free
    buildCommand: "npm install && npm run build"
    startCommand: "npm run start"
    envVars:
      - key: NEXT_PUBLIC_API_URL
    healthCheckPath: "/"