services:
  - type: web
    name: xclusive-sharp-engine
    env: python
    buildCommand: bash start_render_safe.sh
    startCommand: python -m gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
    plan: starter               
    autoDeploy: true
