services:
  - type: web
    name: xclusive-sharp-engine
    env: python
    buildCommand: bash start.sh
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
