services:
  - type: web
    name: xclusive-sharp-engine
    env: python
    buildCommand: bash start.sh
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
    plan: starter               # Optional: define service tier (can be standard, starter, etc.)
    autoDeploy: true           # Optional: auto-deploy new commits (Git-based deployments only)
