services:
  - type: web
    name: xclusive-backend
    env: docker
    branch: master
    region: oregon    # or virginia
    rootDir: backend
    plan: free
    envVars:
      - key: ODDS_API_KEY
        value: 0872bbfe3e80dddd635a1f6d21b09201
      - key: DATABASE_URL
        value: postgresql://xsp_db_user:T67VYY5g9LMBG3DBxohWzAVOYvFrZFSu@dpg-d1rvsuur433s73b8cs1g-a.virginia-postgres.render.com/xsp_db
      - key: JWT_SECRET_KEY
        value: supersecretjwtkey123
    buildCommand: |
      python -m pip install --upgrade pip && \
      python -m pip install -r requirements.txt && \
      playwright install-deps && \
      playwright install
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 3
    healthCheckPath: /ping
