services:
  - type: web
    name: xclusive-sharp-engine
    env: python
    buildCommand: bash start.sh
    startCommand: python app.py   # ✅ this line is key
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
    plan: starter
    autoDeploy: true
