
# utils/team_name_map.py

TEAM_NAME_MAP = {
    "NY Yankees": "New York Yankees",
    "New York Yankees": "New York Yankees",
    "LA Dodgers": "Los Angeles Dodgers",
    "Los Angeles Dodgers": "Los Angeles Dodgers",
    "Chi Cubs": "Chicago Cubs",
    "Chicago Cubs": "Chicago Cubs",
    "SF Giants": "San Francisco Giants",
    "San Francisco Giants": "San Francisco Giants",
    "Bos Red Sox": "Boston Red Sox",
    "Boston Red Sox": "Boston Red Sox",
    "Atl Braves": "Atlanta Braves",
    "Atlanta Braves": "Atlanta Braves",
    "Orioles": "Baltimore Orioles",
    "Baltimore Orioles": "Baltimore Orioles",
    "Red Sox": "Boston Red Sox",
    "Braves": "Atlanta Braves",
    "Yankees": "New York Yankees",
    "Dodgers": "Los Angeles Dodgers",
    "Cubs": "Chicago Cubs",
    "Giants": "San Francisco Giants",
    "Blue Jays": "Toronto Blue Jays",
    "Toronto Blue Jays": "Toronto Blue Jays",
    "Padres": "San Diego Padres",
    "San Diego Padres": "San Diego Padres",
    "Phillies": "Philadelphia Phillies",
    "Philadelphia Phillies": "Philadelphia Phillies",
    "Cardinals": "St. Louis Cardinals",
    "St. Louis Cardinals": "St. Louis Cardinals",
    "Astros": "Houston Astros",
    "Houston Astros": "Houston Astros",
    "Pirates": "Pittsburgh Pirates",
    "Pittsburgh Pirates": "Pittsburgh Pirates",
    "Rangers": "Texas Rangers",
    "Texas Rangers": "Texas Rangers",
    "Rockies": "Colorado Rockies",
    "Colorado Rockies": "Colorado Rockies",
    "Angels": "Los Angeles Angels",
    "Los Angeles Angels": "Los Angeles Angels",
    "Athletics": "Oakland Athletics",
    "Oakland Athletics": "Oakland Athletics",
    "Diamondbacks": "Arizona Diamondbacks",
    "Arizona Diamondbacks": "Arizona Diamondbacks",
    "Guardians": "Cleveland Guardians",
    "Cleveland Guardians": "Cleveland Guardians",
    "Tigers": "Detroit Tigers",
    "Detroit Tigers": "Detroit Tigers",
    "Marlins": "Miami Marlins",
    "Miami Marlins": "Miami Marlins",
    "Royals": "Kansas City Royals",
    "Kansas City Royals": "Kansas City Royals",
    "Nationals": "Washington Nationals",
    "Washington Nationals": "Washington Nationals",
    "Twins": "Minnesota Twins",
    "Minnesota Twins": "Minnesota Twins",
    "Brewers": "Milwaukee Brewers",
    "Milwaukee Brewers": "Milwaukee Brewers",
    "Mariners": "Seattle Mariners",
    "Seattle Mariners": "Seattle Mariners",
    "White Sox": "Chicago White Sox",
    "Chicago White Sox": "Chicago White Sox",
    "Mets": "New York Mets",
    "New York Mets": "New York Mets",
    "Rays": "Tampa Bay Rays",
    "Tampa Bay Rays": "Tampa Bay Rays",
    "CWS": "Chicago White Sox",
    "SD": "San Diego Padres",
    "LAD": "Los Angeles Dodgers",
    "CHC": "Chicago Cubs",
    "CLE": "Cleveland Guardians",
    "KC": "Kansas City Royals",
    "MIA": "Miami Marlins",
    "PHI": "Philadelphia Phillies",
    "SF": "San Francisco Giants",
    "TOR": "Toronto Blue Jays",
    "TEX": "Texas Rangers",
    "SEA": "Seattle Mariners",
    "OAK": "Oakland Athletics",
    "BAL": "Baltimore Orioles",
    "NYY": "New York Yankees",
    "ATL": "Atlanta Braves",
    "PIT": "Pittsburgh Pirates",
    "MIL": "Milwaukee Brewers",
    "ARI": "Arizona Diamondbacks",
    "LAA": "Los Angeles Angels"
}

def normalize_team_name(raw_name):
    return TEAM_NAME_MAP.get(raw_name.strip(), raw_name.strip())
